version: '3'

services:
  frontend:
    image: fe:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000/generate-qr/

  backend:
    image: be:latest
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
